tango_with_django_project/rango/urls.py
from django.urls import path
from rango import views

app_name = 'rango'
urlpatterns = [
    path(r'', views.index, name="index"),
    path(r'about/', views.about, name="about"),
    path(r'category/<slug:category_name_slug>/', views.show_category, name="show_category"),
    path(r'add_category/', views.add_category, name='add_category'),
    path(r'category/<slug:category_name_slug>/add_page/', views.add_page, name='add_page'),
    # path(r'register/', views.register, name='register'),
    # path(r'login/', views.user_login, name='login'),
    path(r'restricted/', views.restricted, name='restricted'),
    path(r'search/', views.search, name='search'),
    path(r'goto/', views.track_url, name='goto'),
    path(r'register_profile/', views.register_profile, name='register_profile'),
    path(r'profile/<slug:username>/', views.profile, name='profile'),
    path(r'like/', views.like_category, name='like_category'),
    path(r'test/', views.test_html, name='test_html'),
    path(r'suggest/', views.suggest_category, name='suggest_category'),
    path(r'add/', views.auto_add_page, name='auto_add_page')
    # path(r'logout/', views.user_logout, name='logout')
]

tango_with_django_project/tango_with_django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from rango import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path(r'', views.index),
    path(r'accounts/register/', views.MyRegistrationView.as_view(), name='registration_register'),
    path(r'accounts/', include('registration.backends.simple.urls')),
    path(r'rango/', include('rango.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tango_with_django_project/rango/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User


class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name


class Page(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)
    last_visit = models.DateTimeField(auto_now=True)
    first_visit = models.DateTimeField()

    def __str__(self):
        return self.title


class UserProfile(models.Model):
    # 这一行是必须的
    # 建立与 User 模型之间的关系
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # 想增加的属性
    website = models.URLField(blank=True)
    # 此外，注意 ImageField 字段的 upload_to 参数。这个参数的值与项目的 MEDIA_ROOT 设置
    # （第 4 章）结合在一起，确定上传的头像存储在哪里。假如 MEDIA_ROOT 的值为
    # <workspace>/tango_with_django_project/media/，upload_to 参数的值为 profile_images，那么头
    # 像将存储在<workspace>/tango_with_django_project/media/profile_images/ 目录中。
    picture = models.ImageField(upload_to='profile_images', blank=True)

    # 覆盖 __str__() 方法，返回有意义的字符串
    # 如果使用 python2.7.x，还要返回 __unicode__ 方法
    def __str__(self):
        return self.user.username

tango_with_django_project/rango/forms.py
from django import forms
from rango.models import Page, Category, UserProfile
from django.contrib.auth.models import User


class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128,
                           help_text="Please enter the category name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    # 嵌套的类，为表单提供额外信息
    class Meta:
        # 把这个 ModelForm 与一个模型连接
        model = Category
        fields = ('name',)


class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128,
                            help_text="please enter the tittle of the page.")
    url = forms.URLField(max_length=200,
                         help_text="Please enter the URL of the page")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        # 把这个 ModelForm 与一个模型连接起来
        model = Page

        # 想在表单中放那些字段？
        # 有时不需要全部字段
        # 有些字段接受空值，因此可能无需显示
        # 这里我们想隐藏外键字段

        # 为此，可以排除 category 字段
        exclude = ('category',)

        # 也可以直接指定想显示的字段（不含 category 字段）
        # fields = ('title', 'url', 'views')

    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')

        # 如果 url 字段不为空， 且不以"https://"开头
        # 在前面加上"http://"
        if url and not url.startswith('http://'):
            url = 'http://' + url
            cleaned_data['url'] = url
        return cleaned_data


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class UserProfileForm(forms.ModelForm):
    website = forms.URLField(required=False)
    picture = forms.ImageField(required=False)

    class Meta:
        model = UserProfile
        exclude = ('user',)

tango_with_django_project/rango/views.py
from django.shortcuts import render
from rango.models import Category
from rango.models import Page, UserProfile
from rango.forms import CategoryForm, PageForm, UserProfileForm, UserForm, UserProfileForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from datetime import datetime
from rango.webhose_search import run_query
from registration.backends.simple.views import RegistrationView


class MyRegistrationView(RegistrationView):
    # 自定义一个类，覆盖 registration.backends.simple.views 提供的 RegistrationView
    # 用户注册成功后重定向
    def get_success_url(self, user=None):
        return reverse('rango:register_profile')


def index(request):
    # 查询数据库，获取目前存储的所有分类
    # 按点赞次数倒序排列分类
    # 获取前5个分类（如果分类数少于5个，那就获取全部）
    # 把分类列表放入 context_dict 字典
    # 稍后传给模板引擎

    category_list = Category.objects.order_by('-likes')[:5]
    page_list = Page.objects.order_by('-views')[:5]
    context_dict = {'categories': category_list,
                    'pages': page_list}

    # 调用处理 cookie 的辅助函数
    # print('======>: ' + datetime.now().strftime('%Y%m%d%H%M%S'))
    visitor_cookie_handle(request)
    context_dict['visits'] = request.session['visits']

    # 返回
    response = render(request, 'rango/index.html', context_dict)
    return response


def about(request):

    if request.session.test_cookie_worked():
        print("TEST COOKIE WORKED!")
        request.session.delete_test_cookie()

    # 打印请求方法
    print(request.method)
    # 打印用户名
    print(request.user)
    context_dict = {'message': "This tutorial has been put together by <your-name>.",
                    'visits': request.session['visits']}
    return render(request, 'rango/about.html', context=context_dict)


def show_category(request, category_name_slug):
    # 创建上下文字典，稍后传给模板渲染引擎
    context_dict = {}

    try:
        # 能通过传入的分类别名找到对应的分类吗？
        # 如果找不到，.get() 方法抛出 DoesNotExist 异常
        # 因此 .get() 方法返回一个模型实例或者抛出异常
        category = Category.objects.get(slug=category_name_slug)

        # 检索关联的所有网页
        # 注意， filter()返回一个网页对象列表或者空列表
        pages = Page.objects.filter(category=category)

        # 把得到的列表赋值给模板上下文中名为 pages 的键
        context_dict['pages'] = pages
        context_dict['category'] = category

    except Category.DoesNotExist:
        context_dict['category'] = None
        context_dict['pages'] = None

    result_list = []
    if request.method == 'POST':
        query = request.POST['query'].strip()
        if query:
            result_list = run_query(query)
            context_dict['query'] = query
    context_dict['result_list'] = result_list

    # 渲染响应，返回给客户端
    return render(request, 'rango/category.html', context_dict)


@login_required
def add_category(request):
    form = CategoryForm()
    # 是 HTTP POST 请求吗
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        # 表单数据有效吗
        if form.is_valid():
            # 把新分类存入数据库
            form.save(commit=True)
            # 保存新分类后可以显示一个确认消息
            # 不过既然最受欢迎的分类在首页
            # 那就把用户带到首页吧
            return index(request)
        else:
            # 表单数据有错误
            # 直接在终端里打印出来
            print(form.errors)
    # 处理有效和无效数据后之后
    # 渲染表单，并显示可能出现的错误消息
    return render(request, 'rango/add_category.html', {'form': form})


@login_required
def add_page(request, category_name_slug):
    try:
        # 通过 category_name_slug 在数据库中 category
        category = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        category = None

    form = PageForm()
    if request.method == 'POST':
        form = PageForm(request.POST)
        if form.is_valid():
            page = form.save(commit=False)
            page.category = category
            page.views = 0
            page.save()
            return show_category(request, category_name_slug)
        else:
            print(form.errors)

    print(form.is_valid())
    print(form.errors)

    context_dict = {'form': form, 'category': category}
    return render(request, 'rango/add_page.html', context_dict)


def register(request):
    # 一个布尔值，告诉模板注册是否成功
    # 一开始设为 False， 注册成功后改为 True
    registered = False

    # 如果是 HTTP POST 请求，处理表单数据
    if request.method == 'POST':
        # 尝试获取原始表单数据
        # 注意，UserForm 和 UserProfileForm 中的数据都需要
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

        # 如果两个表单中的数据是有效的
        if user_form.is_valid() and profile_form.is_valid():
            # 把 UserForm 中的数据存入数据库
            user = user_form.save()

            # 使用 set_password 方法计算密码哈希值
            # 然后更行 user 对象
            user.set_password(user.password)
            user.save()

            # 现在处理 UserProfile 实例
            # 因为要自行处理 user 属性，所以设定 commit=False
            # 延迟保存模型，以防出现完整性问题
            profile = profile_form.save(commit=False)
            profile.user = user

            # 用户提供了头像了吗
            # 如果提供了，从表单数据库中提取出来， 赋给UserProfile 模型
            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']

            # 保存实例
            profile.save()

            # 更新变量的值，告诉模板注册成功了
            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        # 不是 POST 请求， 渲染两个 ModelForm 实例
        # 表单为空，待用户填写
        user_form = UserForm()
        profile_form = UserProfileForm()

    return render(request,
                  'rango/register.html',
                  {'user_form': user_form,
                   'profile_form': profile_form,
                   'registered': registered})


@login_required
def register_profile(request):
    form = UserProfileForm()

    if request.method == 'POST':
        form = UserProfileForm(request.POST, request.FILES)
        if form.is_valid():
            user_profile = form.save(commit=False)
            user_profile.user = request.user
            user_profile.save()

            return HttpResponseRedirect(reverse('rango:index'))
        else:
            print(form.errors)

    context_dict = {'form': form}

    return render(request, 'rango/profile_registration.html', context_dict)


def user_login(request):
    # 如果是 HTTP POST 请求，尝试提取相关信息
    if request.method == 'POST':
        # 获取用户在登陆表单中输入的用户名和密码
        # 我们使用的是 request.POST.get('<variable>')
        # 而不是 request.POST['<>']
        # 而后者抛 KeyError 异常
        username = request.POST.get('username')
        password = request.POST.get('password')

        # 使用 Django 提供的函数检查 username/password 是否有效
        # 如果有效，返回一个 User 对象
        user = authenticate(username=username, password=password)

        # 如果得到了 User 对象，说明用户输入的凭据是对的
        # 如果是 None (Python 表示没有值得方式)，说明没找到与凭据匹配的用户
        if user:
            # 账户是否激活，或者被禁了
            if user.is_active:
                # 登入有效并且已经激活的账户
                # 然后重定向到首页
                login(request, user)
                return HttpResponseRedirect(reverse('rango:index'))
            else:
                # 未激活
                return render(request, 'rango/login.html', {})
        else:
            # 提供的登陆凭证无效
            print("Invalid login details: {0}, {1}".format(username, password))
            return render(request, 'rango/login.html', {})
    else:
        # 不是 POST 请求，显示登陆表单
        return render(request, 'rango/login.html', {})


# 装饰器模式
@login_required
def restricted(request):
    return render(request, 'rango/restricted.html', {})


# 装饰器限制，只有登陆了的用户才能访问这个试图
@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('rango:index'))


# 辅助函数
def get_server_side_cookie(request, cookie_name, default_val=None):
    val = request.session.get(cookie_name)
    if not val:
        val = default_val
    return val


def visitor_cookie_handle(request):
    visits = int(get_server_side_cookie(request, 'visits', '1'))

    last_visit_cookie = get_server_side_cookie(request, 'last_visit', str(datetime.now()))
    last_visit_time = datetime.strptime(last_visit_cookie[:-7],
                                        '%Y-%m-%d %H:%M:%S')

    # 如果距上次访问已超过一天
    if (datetime.now() - last_visit_time).seconds > 10:
        visits += 1
        # 更新
        # response.set_cookie('last_visit', str(datetime.now()))
        request.session['last_visit'] = str(datetime.now())
    else:
        # response.set_cookie('last_visit', last_visit_cookie)
        request.session['last_visit'] = last_visit_cookie

    request.session['visits'] = visits


def search(request):

    result_list = []
    query = ''
    if request.method == 'POST':
        query = request.POST['query'].strip()
        if query:
            result_list = run_query(query)

    return render(request, 'rango/search.html', {'result_list': result_list, 'query': query})


def track_url(request):
    page_id = None
    if request.method == 'GET':
        if 'page_id' in request.GET:
            page_id = request.GET['page_id']
            page = Page.objects.get(id=page_id)
            page.views += 1
            page.save()
            print('page.views: %d' % page.views)
            return HttpResponseRedirect(page.url)
    return HttpResponseRedirect(reverse('rango:index'))


@login_required
def profile(request, username):
    try:
        user = User.objects.get(username=username)
    except User.DoesNotExist:
        return HttpResponseRedirect(reverse('rango:index'))

    userprofile = UserProfile.objects.get_or_create(user=user)[0]
    form = UserProfileForm(
        {'website': userprofile.website, 'picture': userprofile.picture})

    if request.method == 'POST' and request.user.id == userprofile.user.id:
        form = UserProfileForm(request.POST, request.FILES, instance=userprofile)
        if form.is_valid:
            form.save(commit=True)

tango_with_django_project/templates/rango/add_category.html
{% extends 'rango/base.html' %}
{% load bootstrap3 %}

{% block title_block %}
    Add_category
{% endblock %}

{% block body_block %}


        <form role="form" id="category_form" method="post"
              action="{% url 'rango:add_category' %}">
        <h2 class="form-signin-heading">Add a Category</h2>
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button type="submit" class="btn btn-primary">
                {% bootstrap_icon "star" %} Submit
            </button>
        {% endbuttons %}
        </form>

{% endblock %}

tango_with_django_project/templates/rango/add_page.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Add_Page
{% endblock %}

{% block body_block %}
    {% if category %}
            <form role="form" id="page_form" method="post"
              action="{% url 'rango:add_page' category.slug %}">
            <h2 class="form-signin-heading">Add a Page to
                <a href="{% url 'rango:show_category' category.slug %}">{{ category.name }}</a>
            </h2>
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}
            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}<br/>
                {{ field }} <br/>
            {% endfor %}
             <br/>
             <button class="btn btn-primary"
                        type="submit" name="submit">
                Add Page
             </button>
        </form>
    {% else %}
        <p>This is category does not exist.</p>
    {% endif %}



{% endblock %}

tango_with_django_project/templates/rango/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}
<html lang="en">


  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="http://v4-alpha.getbootstrap.com/favicon.ico">

    <title>
        Rango - {% block title %} How to Tango with Django! {% endblock %}
    </title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/dashboard/">

    <!-- Bootstrap core CSS -->
    <link href="http://v4-alpha.getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="https://v4-alpha.getbootstrap.com/examples/dashboard/dashboard.css" rel="stylesheet">
  </head>

  <body>
    <nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse">
      <button class="navbar-toggler navbar-toggler-right hidden-lg-up" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <a class="navbar-brand" href="{% url 'rango:index' %}">Rango</a>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'rango:index' %}">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'rango:about' %}">About</a>
          </li>
            {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'rango:restricted' %}">Restricted Page</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'rango:add_category' %}">Add a New Category</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'auth_logout' %}?next=/rango/">Logout</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'rango:search' %}">Search</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'rango:profile' user.username %}">Profile</a>
          </li>
            {% else %}
           <li class="nav-item">
            <a class="nav-link" href="{% url 'registration_register' %}">Register Here</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'auth_login' %}">Login</a>
          </li>
            {% endif %}
        </ul>

        <!--注释掉搜索框-->
        <!--<form class="form-inline mt-2 mt-md-0">
          <input class="form-control mr-sm-2" type="text" placeholder="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>-->
      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <nav class="col-sm-3 col-md-2 hidden-xs-down bg-faded sidebar">
          <ul class="nav nav-list flex-column">
            <li class="nav-item">Type to find a category</li>
            <form>
              <li class="nav-item"><input class="search-query form-control" type="text"
                  name="suggestion" value="" id="suggestion" />
              </li>
            </form>
          </ul>
          <hr>
          <div id="cats">
          </div>
        </nav>

        <main class="col-sm-9 offset-sm-3 col-md-10 offset-md-2 pt-3">
            {% block body_block %}
            {% endblock %}
        </main>
      </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://cdn.staticfile.org/jquery/3.1.1/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="http://v4-alpha.getbootstrap.com/assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="http://v4-alpha.getbootstrap.com/dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="http://v4-alpha.getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js"></script>
    <script src="{% static 'js/rango-ajax.js' %}"></script>

  </body>

tango_with_django_project/templates/rango/base_bootstrap.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}
<html lang="en">


  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="http://v4-alpha.getbootstrap.com/favicon.ico">

    <title>
        Rango - {% block title %} How to Tango with Django! {% endblock %}
    </title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/dashboard/">

    <!-- Bootstrap core CSS -->
    <link href="http://v4-alpha.getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="https://v4-alpha.getbootstrap.com/examples/dashboard/dashboard.css" rel="stylesheet">
  </head>

  <body>
    <nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse">
      <button class="navbar-toggler navbar-toggler-right hidden-lg-up" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="{% url 'rango:index' %}">Rango</a>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'rango:index' %}">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'rango:about' %}">About</a>
          </li>
            {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'rango:restricted' %}">Restricted Page</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'rango:add_category' %}">Add a New Category</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'auth_logout' %}?next=/rango/">Logout</a>
          </li>
            {% else %}
           <li class="nav-item">
            <a class="nav-link" href="{% url 'registration_register' %}">Register Here</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'auth_login' %}">Login</a>
          </li>
            {% endif %}
        </ul>
        <form class="form-inline mt-2 mt-md-0">
          <input class="form-control mr-sm-2" type="text" placeholder="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <nav class="col-sm-3 col-md-2 hidden-xs-down bg-faded sidebar">
            {% block sidebar_block %}
                {% get_category_list category %}
            {% endblock %}
        </nav>

        <main class="col-sm-9 offset-sm-3 col-md-10 offset-md-2 pt-3">
            {% block body_block %}
            {% endblock %}
        </main>
      </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="http://v4-alpha.getbootstrap.com/assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="http://v4-alpha.getbootstrap.com/dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="http://v4-alpha.getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>

tango_with_django_project/templates/rango/cats.html
<div class="container">
<ul class="nav nav-pills flex-column">
{% for c in cats %}
    {% if c == act_cat %}
        <li class="nav-item">
            <strong>
                <a class="nav-link active" href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a>
            </strong>
        </li>
    {% else %}
        <li class="nav-item">
            <a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a>
        </li>
    {% endif %}
{% endfor %}
</ul>
</div>

tango_with_django_project/templates/rango/index.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Home
{% endblock %}

{% block body_block %}
<div class="jumbotron">
    <h1 class="diplay-3">Rango says...</h1>
    {% if user.is_authenticated %}
        <h1>hey there {{ user.username }}!</h1>
    {% else %}
        <h1>hey there partner!</h1>
    {% endif %}
</div>

<div class="row marketing">
    <div class="col-lg-6">
        <h4>Most Liked Categories</h4>
        <p>
            {% if categories %}
            <ul class="list-group">
                {% for category in categories %}
                    <li class="list-group-item">
                        <a href="{% url 'rango:show_category' category.slug %}">{{ category.name }}</a>
                    </li>
                {% endfor %}
            </ul>
            {% else %}
             <strong>There are no categories present</strong>
            {% endif %}
        </p>
    </div>

    <div class="col-lg-6">
        <h4>Most Viewed Pages</h4>
        <p>
            {% if pages %}
            <ul class="list-group">
                {% for page in pages %}
                    <li class="list-group-item">
                        <a href="{{ page.url }}">{{ page.title }}</a>
                    </li>
                {% endfor %}
            </ul>
            {% else %}
                <strong>There are no categories present</strong>
            {% endif %}
        </p>
    </div>
</div>

{% endblock %}

tango_with_django_project/templates/rango/page_list.html
{% if pages %}
    <ul>
        {% for page in pages %}
    <li><a href="{% url 'rango:goto' %}?page_id={{page.id}}"\>{{ page.title }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <strong>No pages currently in category.</strong>
{% endif %}

tango_with_django_project/templates/rango/restricted.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    restricted
{% endblock %}

{% block body_block %}

{% endblock %}